export const MOCK_MOVIES = [
  {
    id: 157336,
    title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    release_date: '2014-11-05',
    vote_average: 8.4,
    vote_count: 36240,
    genre_ids: [12, 18, 878],
    genres: [{ id: 12, name: 'Adventure' }, { id: 18, name: 'Drama' }, { id: 878, name: 'Science Fiction' }],
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    runtime: 169,
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    status: 'Released',
    budget: 165000000,
    revenue: 730784018,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 923, name: 'Legendary Pictures' }, { id: 9996, name: 'Syncopy' }],
    trailer_key: 'zSWdZVtXT7E'
  },
  {
    id: 693134,
    title: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    release_date: '2024-02-27',
    vote_average: 8.2,
    vote_count: 5800,
    genre_ids: [878, 12],
    genres: [{ id: 878, name: 'Science Fiction' }, { id: 12, name: 'Adventure' }],
    poster_path: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5200SV.jpg',
    runtime: 166,
    tagline: 'Long live the fighters.',
    status: 'Released',
    budget: 190000000,
    revenue: 714444358,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 923, name: 'Legendary Pictures' }],
    trailer_key: 'Way9Dexny3w'
  },
  {
    id: 155,
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of allies Lt. Jim Gordon and DA Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    release_date: '2008-07-16',
    vote_average: 8.5,
    vote_count: 33400,
    genre_ids: [18, 28, 80, 53],
    genres: [{ id: 18, name: 'Drama' }, { id: 28, name: 'Action' }, { id: 80, name: 'Crime' }, { id: 53, name: 'Thriller' }],
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    runtime: 152,
    tagline: 'Welcome to a world without rules.',
    status: 'Released',
    budget: 185000000,
    revenue: 1004558444,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 429, name: 'DC Comics' }, { id: 9996, name: 'Syncopy' }],
    trailer_key: 'EXeTwQWrcwY'
  },
  {
    id: 533535,
    title: 'Deadpool & Wolverine',
    overview: 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
    release_date: '2024-07-24',
    vote_average: 7.7,
    vote_count: 6100,
    genre_ids: [28, 35, 878],
    genres: [{ id: 28, name: 'Action' }, { id: 35, name: 'Comedy' }, { id: 878, name: 'Science Fiction' }],
    poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdrop_path: '/yDHYTfA3R0jFYba16jBB1jv8uaC.jpg',
    runtime: 128,
    tagline: 'Come together.',
    status: 'Released',
    budget: 200000000,
    revenue: 1337000000,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 420, name: 'Marvel Studios' }],
    trailer_key: '73_1biulkYk'
  },
  {
    id: 27205,
    title: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    release_date: '2010-07-15',
    vote_average: 8.4,
    vote_count: 36700,
    genre_ids: [28, 878, 12],
    genres: [{ id: 28, name: 'Action' }, { id: 878, name: 'Science Fiction' }, { id: 12, name: 'Adventure' }],
    poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_path: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    runtime: 148,
    tagline: 'Your mind is the scene of the crime.',
    status: 'Released',
    budget: 160000000,
    revenue: 836836967,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }, { english_name: 'Japanese', iso_639_1: 'ja' }],
    production_companies: [{ id: 9996, name: 'Syncopy' }, { id: 923, name: 'Legendary Pictures' }],
    trailer_key: 'YoHD9XEInc0'
  },
  {
    id: 945961,
    title: 'Alien: Romulus',
    overview: 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
    release_date: '2024-08-13',
    vote_average: 7.3,
    vote_count: 2700,
    genre_ids: [27, 878],
    genres: [{ id: 27, name: 'Horror' }, { id: 878, name: 'Science Fiction' }],
    poster_path: '/b33nnKl1GSFbao8l3fZkyRdfPQA.jpg',
    backdrop_path: '/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg',
    runtime: 119,
    tagline: 'In space no one can hear you.',
    status: 'Released',
    budget: 80000000,
    revenue: 350000000,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 25, name: '20th Century Studios' }, { id: 1645, name: 'Scott Free Productions' }],
    trailer_key: 'x0XDEhP4MQs'
  },
  {
    id: 299536,
    title: 'Avengers: Infinity War',
    overview: 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos.',
    release_date: '2018-04-25',
    vote_average: 8.3,
    vote_count: 29800,
    genre_ids: [12, 28, 878],
    genres: [{ id: 12, name: 'Adventure' }, { id: 28, name: 'Action' }, { id: 878, name: 'Science Fiction' }],
    poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    backdrop_path: '/mDfJG3LC3Dqb67AZ52x3Z0jOS0c.jpg',
    runtime: 149,
    tagline: 'An entire universe. Once and for all.',
    status: 'Released',
    budget: 300000000,
    revenue: 2046239637,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 420, name: 'Marvel Studios' }],
    trailer_key: '6ZfuNTqbHE8'
  },
  {
    id: 438631,
    title: 'Dune',
    overview: 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.',
    release_date: '2021-09-15',
    vote_average: 7.8,
    vote_count: 11400,
    genre_ids: [878, 12],
    genres: [{ id: 878, name: 'Science Fiction' }, { id: 12, name: 'Adventure' }],
    poster_path: '/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
    backdrop_path: '/lzWHmYXZFiMI89IzWkCwAL92bPt.jpg',
    runtime: 155,
    tagline: 'Beyond fear, destiny awaits.',
    status: 'Released',
    budget: 165000000,
    revenue: 402027830,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 923, name: 'Legendary Pictures' }],
    trailer_key: '8g18jFHCLXk'
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II.',
    release_date: '2023-07-19',
    vote_average: 8.1,
    vote_count: 9400,
    genre_ids: [18, 36],
    genres: [{ id: 18, name: 'Drama' }, { id: 36, name: 'History' }],
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    runtime: 181,
    tagline: 'The world forever changes.',
    status: 'Released',
    budget: 100000000,
    revenue: 957000000,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 9996, name: 'Syncopy' }, { id: 33, name: 'Universal Pictures' }],
    trailer_key: 'uYPbbksJxIg'
  },
  {
    id: 76600,
    title: 'Avatar: The Way of Water',
    overview: 'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    release_date: '2022-12-14',
    vote_average: 7.6,
    vote_count: 11200,
    genre_ids: [878, 12, 28],
    genres: [{ id: 878, name: 'Science Fiction' }, { id: 12, name: 'Adventure' }, { id: 28, name: 'Action' }],
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    backdrop_path: '/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
    runtime: 192,
    tagline: 'Return to Pandora.',
    status: 'Released',
    budget: 350000000,
    revenue: 2320250281,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 574, name: 'Lightstorm Entertainment' }],
    trailer_key: 'd9MyW72ELq0'
  },
  {
    id: 238,
    title: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
    release_date: '1972-03-14',
    vote_average: 8.7,
    vote_count: 20400,
    genre_ids: [18, 80],
    genres: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }],
    poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop_path: '/tmU7GeKVybMWF92vGZSDTMKhitY.jpg',
    runtime: 175,
    tagline: 'An offer you can\'t refuse.',
    status: 'Released',
    budget: 6000000,
    revenue: 245066411,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }, { english_name: 'Italian', iso_639_1: 'it' }],
    production_companies: [{ id: 4, name: 'Paramount Pictures' }],
    trailer_key: 'UaVTIH8mujA'
  },
  {
    id: 550,
    title: 'Fight Club',
    overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    release_date: '1999-10-15',
    vote_average: 8.4,
    vote_count: 29300,
    genre_ids: [18],
    genres: [{ id: 18, name: 'Drama' }],
    poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop_path: '/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    runtime: 139,
    tagline: 'Mischief. Mayhem. Soap.',
    status: 'Released',
    budget: 63000000,
    revenue: 100853753,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en' }],
    production_companies: [{ id: 508, name: 'Regency Enterprises' }, { id: 711, name: 'Fox 2000 Pictures' }],
    trailer_key: 'qtRKdVHc-cE'
  }
];

export const MOCK_CAST = {
  157336: [
    { id: 10297, name: 'Matthew McConaughey', character: 'Joseph Cooper', profile_path: '/e9ZHRY5DaJQ2vwzguh8uW09L2PX.jpg' },
    { id: 1813, name: 'Anne Hathaway', character: 'Dr. Amelia Brand', profile_path: '/tLel4qkSJvMb9FQ771Ns6Lhuwh7.jpg' },
    { id: 83002, name: 'Jessica Chastain', character: 'Murphy Cooper', profile_path: '/lodMzLKSbtrK1zbflg4CSrjwbBP.jpg' },
    { id: 3895, name: 'Michael Caine', character: 'Professor John Brand', profile_path: '/bVvlhmvPU1iISzWC259c762r5i9.jpg' },
    { id: 1892, name: 'Matt Damon', character: 'Dr. Mann', profile_path: '/elSlNgV8xVifsbHpFsqrCiuvUtZ.jpg' },
    { id: 1893, name: 'Mackenzie Foy', character: 'Murph (Young)', profile_path: '/o0pYf2pG0Q3nF6wL2t8nJ3Pq9m8.jpg' },
    { id: 1894, name: 'John Lithgow', character: 'Donald', profile_path: '/890W1Nq9qD5wT4eG9iY6gB3z7n0.jpg' },
    { id: 1895, name: 'Timothée Chalamet', character: 'Tom (Young)', profile_path: '/BE2sdjpgsa2rNTFa66f7upkaOP.jpg' }
  ],
  693134: [
    { id: 1190668, name: 'Timothée Chalamet', character: 'Paul Atreides', profile_path: '/BE2sdjpgsa2rNTFa66f7upkaOP.jpg' },
    { id: 505710, name: 'Zendaya', character: 'Chani', profile_path: '/r2QfVjQeCj2H8hZJq5wX9q8f8t0.jpg' },
    { id: 932, name: 'Rebecca Ferguson', character: 'Lady Jessica Atreides', profile_path: '/lJloTOheuQSirSLnRna3JH0vyvP.jpg' },
    { id: 7467, name: 'Javier Bardem', character: 'Stilgar', profile_path: '/gO9x4o6DkY9vJ4g9sE4x0y4k4g4.jpg' },
    { id: 1373737, name: 'Florence Pugh', character: 'Princess Irulan', profile_path: '/75hWHuhgVj4L8H7iH7m0n0p9p0p.jpg' },
    { id: 1391974, name: 'Austin Butler', character: 'Feyd-Rautha Harkonnen', profile_path: '/2dGHc1JgS8C0s0k0v0m0n0k0p0o.jpg' }
  ],
  155: [
    { id: 3894, name: 'Christian Bale', character: 'Bruce Wayne / Batman', profile_path: '/qCpZn2e3nWew0P456f4dD3N7G9L.jpg' },
    { id: 1810, name: 'Heath Ledger', character: 'Joker', profile_path: '/5Y9HnYYa9jF4DY5Sc76KxO9O4Kx.jpg' },
    { id: 3895, name: 'Michael Caine', character: 'Alfred Pennyworth', profile_path: '/bVvlhmvPU1iISzWC259c762r5i9.jpg' },
    { id: 64, name: 'Gary Oldman', character: 'James Gordon', profile_path: '/2v9Fs9fA8vC4H9d9N4G9M3P5Q1A.jpg' },
    { id: 192, name: 'Morgan Freeman', character: 'Lucius Fox', profile_path: '/jPsLqiYGSofU4s6BjrxnefMfabb.jpg' }
  ]
};

export const getMockCastForMovie = (id) => {
  return MOCK_CAST[id] || [
    { id: 101, name: 'Lead Actor', character: 'Protagonist', profile_path: null },
    { id: 102, name: 'Co-Star', character: 'Companion', profile_path: null },
    { id: 103, name: 'Supporting Role', character: 'Mentor', profile_path: null },
    { id: 104, name: 'Guest Appearance', character: 'Special Ally', profile_path: null }
  ];
};
