export const FETCH_POPULAR_REQUEST = 'FETCH_POPULAR_REQUEST';
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS';
export const FETCH_POPULAR_FAILURE = 'FETCH_POPULAR_FAILURE';

export const FETCH_TRENDING_REQUEST = 'FETCH_TRENDING_REQUEST';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
export const FETCH_TRENDING_FAILURE = 'FETCH_TRENDING_FAILURE';

export const FETCH_UPCOMING_REQUEST = 'FETCH_UPCOMING_REQUEST';
export const FETCH_UPCOMING_SUCCESS = 'FETCH_UPCOMING_SUCCESS';
export const FETCH_UPCOMING_FAILURE = 'FETCH_UPCOMING_FAILURE';

export const FETCH_TOP_RATED_REQUEST = 'FETCH_TOP_RATED_REQUEST';
export const FETCH_TOP_RATED_SUCCESS = 'FETCH_TOP_RATED_SUCCESS';
export const FETCH_TOP_RATED_FAILURE = 'FETCH_TOP_RATED_FAILURE';

export const FETCH_NOW_PLAYING_REQUEST = 'FETCH_NOW_PLAYING_REQUEST';
export const FETCH_NOW_PLAYING_SUCCESS = 'FETCH_NOW_PLAYING_SUCCESS';
export const FETCH_NOW_PLAYING_FAILURE = 'FETCH_NOW_PLAYING_FAILURE';

export const FETCH_DISCOVER_REQUEST = 'FETCH_DISCOVER_REQUEST';
export const FETCH_DISCOVER_SUCCESS = 'FETCH_DISCOVER_SUCCESS';
export const FETCH_DISCOVER_FAILURE = 'FETCH_DISCOVER_FAILURE';

export const FETCH_MOVIE_DETAILS_REQUEST = 'FETCH_MOVIE_DETAILS_REQUEST';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const FETCH_MOVIE_DETAILS_FAILURE = 'FETCH_MOVIE_DETAILS_FAILURE';

export const FETCH_CREDITS_REQUEST = 'FETCH_CREDITS_REQUEST';
export const FETCH_CREDITS_SUCCESS = 'FETCH_CREDITS_SUCCESS';
export const FETCH_CREDITS_FAILURE = 'FETCH_CREDITS_FAILURE';

export const FETCH_SIMILAR_REQUEST = 'FETCH_SIMILAR_REQUEST';
export const FETCH_SIMILAR_SUCCESS = 'FETCH_SIMILAR_SUCCESS';
export const FETCH_SIMILAR_FAILURE = 'FETCH_SIMILAR_FAILURE';

export const FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';

export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const LOAD_FAVORITES = 'LOAD_FAVORITES';

export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const LOAD_WATCHLIST = 'LOAD_WATCHLIST';
